project_id = "ykkspgvhveaeeaisprqz"

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.notify-course-request]
verify_jwt = false

[functions.track-session]
verify_jwt = false

[functions.trigger-processing]
verify_jwt = false

[functions.generate-quiz-options]
verify_jwt = false
