-- Clear quiz_options generated by the old edge function for IRM 104
UPDATE course_questions SET quiz_options = NULL 
WHERE course_id IN (
  SELECT id FROM courses WHERE code = 'IRM 104'
) AND quiz_options IS NOT NULL;

-- Mark stuck uploads as needing reprocessing
UPDATE course_uploads SET status = 'pending' 
WHERE id IN ('161c00ac-8e14-4471-af70-f01fe6b9ea6f', '98eac41d-acc5-4142-98d3-ea3dd7c7cf5d');